seedNamespace: shoot--project--shootname

nameOverride: ""
fullnameOverride: cert-controller-manager

replicaCount: 1

images:
  cert-management: any-repo:any-tag

shootClusterSecret: cert-management-kubecfg

resources:
  requests:
   cpu: 100m
   memory: 128Mi
  limits:
   cpu: 200m
   memory: 384Mi

nodeSelector: {}
tolerations: []
affinity: {}
# priorityClassName: ""

podAnnotations: {}

defaultIssuer:
  retricted: true
  name: garden
  domains: shoot.project.gardener.cloud

issuers:
- name: gardener
  acme:
    email: john.doe@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
  # privateKey: | # Optional key for Let's Encrypt account.
  #   -----BEGIN BEGIN RSA PRIVATE KEY-----
  #   ...
  #   -----END RSA PRIVATE KEY-----
  # privateKeySecretName: my-private-key-secret # alternative to embedded key
  # externalAccountBinding:
  #   keyID: aabbccddeeff
  #   keySecretName: my-eab-key-secret
  # skipDNSChallengeValidation: true
  # domains:
  #   include:
  #   - my.domain.com
  #   exclude:
  #   - private.my.domain.com
# requestsPerDayQuota: 10

shootIssuers:
  enabled: true

dnsChallengeOnShoot:
  enabled: false
  # namespace: kube-system
  # dnsClass: my-class

configuration:
# propagationTimeout: 60s # TTL for DNS01 challenges
  serverPortHttp: 10258
  ingressCertWorkers: 5
  certWorkers: 5
  issuerWorkers: 2
# defaultRequestsPerDayQuota: 50
# precheckNameservers: 8.8.8.8,8.8.4.4
# caCertificates: | # optional custom CA certificates when using private ACME provider
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
#
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  deactivateAuthorizations: true

additionalConfiguration:
- --kubeconfig.disable-deploy-crds
- --source.disable-deploy-crds
- --target.disable-deploy-crds
